-- ECOLI_DATA
CREATE TABLE ECOLI_DATA (
    ID NUMBER NOT NULL,
    PARENT_ID NUMBER,
    SIZE_OF_COLONY INTEGER NOT NULL,
    GENOTYPE INTEGER NOT NULL
);

INSERT INTO ECOLI_DATA
VALUES(1, NULL, 10 ,5);
INSERT INTO ECOLI_DATA
VALUES(2, NULL, 2 ,10);
INSERT INTO ECOLI_DATA
VALUES(3, 2, 100 ,4);
INSERT INTO ECOLI_DATA
VALUES(4, 2, 16 ,4);
INSERT INTO ECOLI_DATA
VALUES(5, 2, 17 ,6);
INSERT INTO ECOLI_DATA
VALUES(6, 4, 101 ,22);
INSERT INTO ECOLI_DATA
VALUES(7, 4, 101 ,23);
INSERT INTO ECOLI_DATA
VALUES(8, 6, 1 ,27);
COMMIT;
-- 비교쿼리1
WITH CTE (ID, PARENT_ID, GENERATION) AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, C.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN CTE C ON E.PARENT_ID = C.ID
)
SELECT COUNT(ID) AS "COUNT", GENERATION
FROM CTE C
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA E
    WHERE E.PARENT_ID = C.ID
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;
-- 비교쿼리2
SELECT COUNT(ID), GENERATION 
FROM (
    SELECT ID, LEVEL AS GENERATION
    FROM ECOLI_DATA
    CONNECT BY PRIOR ID = PARENT_ID
    START WITH PARENT_ID IS NULL
) C
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA E
    WHERE E.PARENT_ID = C.ID
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;